/**
 * Prints the seed as plain SQL on stdout, computed with the same money helpers
 * as the API. Handy when you would rather paste into the Supabase SQL editor
 * than point a Node process at the database:
 *
 *   npm run seed:sql > seed.sql
 */
import { randomUUID } from 'node:crypto';
import { calculateLine, fromPaise, sumLines, toPaise, type LineAmounts } from '../lib/server/utils/money';
import { buildInvoiceNumber } from '../lib/server/utils/invoice-number';
import { customers, invoices, items } from './seed-data';

const q = (value: string | null): string =>
  value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`;

function dateFromOffset(offsetDays: string): string {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + Number(offsetDays));
  return date.toISOString().slice(0, 10);
}

const out: string[] = [
  '-- Generated by `npm run seed:sql`. Safe to re-run: it truncates first.',
  'BEGIN;',
  'TRUNCATE invoice_items, invoices, items, customers RESTART IDENTITY CASCADE;',
  '',
];

const customerIds = new Map<string, string>();
out.push('-- customers ---------------------------------------------------------------');
for (const c of customers) {
  const id = randomUUID();
  customerIds.set(c.key, id);
  out.push(
    `INSERT INTO customers (id, name, email, phone, address, gstin, status) VALUES ` +
      `('${id}', ${q(c.name)}, ${q(c.email)}, ${q(c.phone)}, ${q(c.address)}, ${q(c.gstin)}, ${q(c.status)});`,
  );
}

const itemRows = new Map<string, { id: string; name: string; unit: string; unit_price: string; tax_rate: string }>();
out.push('', '-- items -------------------------------------------------------------------');
for (const i of items) {
  const id = randomUUID();
  itemRows.set(i.key, { id, name: i.name, unit: i.unit, unit_price: i.unit_price, tax_rate: i.tax_rate });
  out.push(
    `INSERT INTO items (id, name, description, unit, unit_price, tax_rate, status) VALUES ` +
      `('${id}', ${q(i.name)}, ${q(i.description)}, ${q(i.unit)}, ${i.unit_price}, ${i.tax_rate}, ${q(i.status)});`,
  );
}

out.push('', '-- invoices ----------------------------------------------------------------');
for (const invoice of invoices) {
  const invoiceDate = dateFromOffset(invoice.invoice_date);
  const invoiceNumber = buildInvoiceNumber(
    Number(invoice.invoice_number),
    new Date(`${invoiceDate}T00:00:00Z`),
  );
  const invoiceId = randomUUID();

  const amounts: LineAmounts[] = [];
  const lines = invoice.lines.map((line, index) => {
    const item = itemRows.get(line.item);
    if (!item) throw new Error(`Seed error: unknown item "${line.item}"`);
    const computed = calculateLine({
      quantity: line.quantity,
      unitPrice: item.unit_price,
      taxRate: item.tax_rate,
    });
    amounts.push(computed);
    return { item, line, computed, lineNo: index + 1 };
  });

  const totals = sumLines(amounts);
  const requested =
    invoice.paid === 'full' ? totals.totalAmount : invoice.paid === 'none' ? 0n : toPaise(invoice.paid);
  const amountPaid = requested > totals.totalAmount ? totals.totalAmount : requested;

  out.push(
    `INSERT INTO invoices (id, invoice_number, customer_id, invoice_date, notes, subtotal, tax_amount, total_amount, amount_paid) VALUES ` +
      `('${invoiceId}', ${q(invoiceNumber)}, '${customerIds.get(invoice.customer)}', ${q(invoiceDate)}, ${q(invoice.notes)}, ` +
      `${fromPaise(totals.subtotal)}, ${fromPaise(totals.taxAmount)}, ${fromPaise(totals.totalAmount)}, ${fromPaise(amountPaid)});`,
  );

  for (const { item, line, computed, lineNo } of lines) {
    out.push(
      `INSERT INTO invoice_items (invoice_id, item_id, item_name_snapshot, item_unit_snapshot, quantity, unit_price, tax_rate, line_subtotal, tax_amount, line_total, line_no) VALUES ` +
        `('${invoiceId}', '${item.id}', ${q(item.name)}, ${q(item.unit)}, ${line.quantity}, ${item.unit_price}, ${item.tax_rate}, ` +
        `${fromPaise(computed.lineSubtotal)}, ${fromPaise(computed.taxAmount)}, ${fromPaise(computed.lineTotal)}, ${lineNo});`,
    );
  }
}

out.push('', 'COMMIT;');
console.log(out.join('\n'));
